//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace EcoPathPortal
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EcoPathDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EcoPathDBEntities object using the connection string found in the 'EcoPathDBEntities' section of the application configuration file.
        /// </summary>
        public EcoPathDBEntities() : base("name=EcoPathDBEntities", "EcoPathDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EcoPathDBEntities object.
        /// </summary>
        public EcoPathDBEntities(string connectionString) : base(connectionString, "EcoPathDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EcoPathDBEntities object.
        /// </summary>
        public EcoPathDBEntities(EntityConnection connection) : base(connection, "EcoPathDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User_Account> User_Accounts
        {
            get
            {
                if ((_User_Accounts == null))
                {
                    _User_Accounts = base.CreateObjectSet<User_Account>("User_Accounts");
                }
                return _User_Accounts;
            }
        }
        private ObjectSet<User_Account> _User_Accounts;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User_Accounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser_Accounts(User_Account user_Account)
        {
            base.AddObject("User_Accounts", user_Account);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EcoPathDBModel", Name="User_Account")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User_Account : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User_Account object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="regDate">Initial value of the RegDate property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="confirmed">Initial value of the Confirmed property.</param>
        public static User_Account CreateUser_Account(global::System.Guid id, global::System.String username, global::System.String password, global::System.DateTime regDate, global::System.String email, global::System.Boolean confirmed)
        {
            User_Account user_Account = new User_Account();
            user_Account.Id = id;
            user_Account.Username = username;
            user_Account.Password = password;
            user_Account.RegDate = regDate;
            user_Account.Email = email;
            user_Account.Confirmed = confirmed;
            return user_Account;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RegDate
        {
            get
            {
                return _RegDate;
            }
            set
            {
                OnRegDateChanging(value);
                ReportPropertyChanging("RegDate");
                _RegDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegDate");
                OnRegDateChanged();
            }
        }
        private global::System.DateTime _RegDate;
        partial void OnRegDateChanging(global::System.DateTime value);
        partial void OnRegDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Confirmed
        {
            get
            {
                return _Confirmed;
            }
            set
            {
                OnConfirmedChanging(value);
                ReportPropertyChanging("Confirmed");
                _Confirmed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Confirmed");
                OnConfirmedChanged();
            }
        }
        private global::System.Boolean _Confirmed;
        partial void OnConfirmedChanging(global::System.Boolean value);
        partial void OnConfirmedChanged();

        #endregion
    
    }

    #endregion
    
}
